[package]
name = "amplion"
version = "0.1.0"
authors = ["mishazawa <macintoshkrug@gmail.com>"]
edition = "2018"

[dependencies]
cpal = "0.11.0"
lazy_static = "1.4.0"

[workspace]
members = [
    "utils",
    "gui"
]
